#!/usr/bin/env bash
# bash completion for myprog
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# autocomplete for myprog
_myprog() {
  local cur prev words cword
  local HELP="--help --version"
  local ARRAY=""

  _init_completion || return

  case $prev in
  -)
    COMPREPLY=($(compgen -W '$HELP' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _myprog -o default myprog
