#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202103251632-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : LICENSE.md
# @ReadME        : README.md
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Thursday, Mar 25, 2021 16:38 EDT
# @File          : bash completion for template
# @Description   :
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# autocomplete for myprog
_myprog() {
  local cur prev words cword
  local HELP="--help --version"
  local ARRAY=""

  _init_completion || return

  case $prev in
  -)
    COMPREPLY=($(compgen -W '$HELP' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _myprog -o default myprog
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end
