#!/usr/bin/env bash
# shellcheck disable=SC2034 # words/cword are unused directly but required
# locals for bash-completion's _init_completion to populate
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202207100807-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  noprompt --help
# @Copyright         :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @Created           :  Sunday, Jul 10, 2022 08:07 EDT
# @File              :  noprompt
# @Description       :
# @TODO              :
# @Other             :
# @Resource          :
# @sudo/root         :  no
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# noprompt completion
__noprompt_completion() {
  local cur prev words cword array shortopts longopts
  shortopts="-e -s -d -h"
  longopts="--enable --show --disable --help --disable-all --enable-all"
  array="date git go lua node path perl php python reminder ruby rust timer wakatime bashprompt"
  _init_completion || return
  if [[ ${cur} == --* ]]; then
    mapfile -t COMPREPLY < <(compgen -W "${longopts}" -- "${cur}")
  elif [[ ${cur} == -* ]]; then
    mapfile -t COMPREPLY < <(compgen -W "${shortopts}" -- "${cur}")
  else
    case $prev in
    --help | -h)
      COMPREPLY=()
      ;;
    *)
      mapfile -t COMPREPLY < <(compgen -W "${array}" -- "${cur}")
      ;;
    esac
  fi
} && complete -F __noprompt_completion -o default noprompt
